name: Build
on: push

jobs:
  build:
    name: Continuous Deployment
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: python3 setup.py develop

      - name: Lint
        run: pylint app/ integration_tests/

      - name: Unit Tests
        run: pytest --cov=app tests/

      - name: Integration Tests
        run: cd integration_tests && docker-compose up integration_tests

      - name: Release
        if: github.ref == 'refs/heads/master'
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        run: |
          curl -X POST -i \
            -H "Authorization: token ${PERSONAL_TOKEN}" \
            -d '{"event_type":"my_finances_build_success"}' \
            https://api.github.com/repos/VinnieApps/vinnieapps-infrastructure/dispatches
